pglombardo/PasswordPusher

app/views/passwords/show.html.haml

Changed “it’s” to “its”, since when used with an apostrophe, “it’s” is
a contraction for “it is”, not a possessive.

Minor typo fix.

---

Gemfile
Gemfile.lock

Fix warnings about insecure protocols, and ensure that gems are downloaded over SSL-protected links. These patches should not impact application behavior in any way, other than to increase security when using Bundler.

Feature: use HTTPS scheme

---

Gemfile
Gemfile.lock

This patch updates the JSON gem to a version compatible with Ruby 2.4.0. In addition, it was necessary to update the Bundler resolution for omniauth-twitter and sass-rails, as they too had a fixed dependency on the unsupported version of the JSON gem.
https://github.com/flori/json/issues/303

Fix JSON compatibility with MRI Ruby 2.4.0

---

app.json
config/environment.rb

These constants can now be configured from ENV-variables (all of them still have default values):
- `PAYLOAD_INITIAL_TEXT`
- `CRYPT_KEY`
- `CRYPT_SALT`
- `EXPIRE_AFTER_DAYS_DEFAULT`
- `EXPIRE_AFTER_DAYS_MIN`
- `EXPIRE_AFTER_DAYS_MAX`
- `EXPIRE_AFTER_VIEWS_DEFAULT`
- `EXPIRE_AFTER_VIEWS_MIN`
- `EXPIRE_AFTER_VIEWS_MAX`
- `DELETABLE_BY_VIEWER_PASSWORDS`
- `DELETABLE_BY_VIEWER_DEFAULT`

Add the possibility to configure some settings using ENV-variables

---

.travis.yml

- Provide a configuration file for integrating the repository with
Travis-CI.
- Caveats:
- There are no tests yet.
- There are gems which should be moved to a production block, as
they aren't needed for testing.
- The repository must be configured to use the Travis-CI webhook
before it will actually run.
Integrating this patch will partially address #46.

Add basic Travis-CI configuration file.

---

app/views/layouts/application.html.haml

A chat client I use has link previews, and it kinda defeats the purpose of the website:
It looks for the meta tag `description`, and failing to find that it toString()'s the body, resulting in what you see.
Adding something like `<meta name="description" content="A password pushing website">` to the html output would help mitigate this issue.

Don't expose password to link previewers

---

app/assets/stylesheets/passwords.css.scss
app/views/passwords/show.html.haml

Improved styling of the input box and copy to clipboard button.

Better styling of the secret link & button to copy to clipboard.

---

Dockerfile

Created this dockerfile for passwordpusher app. It works with docker/openshift/kubernetes too. I could also work on an openshift template to create all the objects + persistent storage if there's no support in the app for mysql.
Image available here: https://hub.docker.com/r/sfarosu/passwordpusher/

dockerfile for the app - image works with openshift/kubernetes too

---

containerization/README.md
containerization/passwordpusher-openshift/template-with-buildconfig.yaml

Hello, got some new goodies :)
New stuff:
- Complete openshift template with all the objects needed to build and deploy passwordpusher.
- Documentation on how to install on openshift.
To do:
- Delete from docker.io the pglombardo/pwpush-openshift repository as we will use a buildconfig so we can build directly in openshift (images will be stored in an imagestream in openshift's repo).
- Delete from the git repo the PasswordPusher/containerization/passwordpusher-openshift/template-with-image.yaml file for the reason above.
- Getting an error after your last commit when running bundle install --without development private test --deployment &&     bundle exec rake assets:precompile && RAILS_ENV=production 
"You are trying to install in deployment mode after changing
your Gemfile. Run `bundle …

Added Openshift template with buildconfig + updated the openshift docs

---

app/views/pages/faq.html.haml

The pwpush FAQ page doesn't have a full green lock in chrome. I think that's because this clicktotweet graphic is served over HTTP. You should change the URL to point to HTTPS instead. Disclaimer: I haven't tested this change except to verify that the image URL works.

Change clicktotweet URL to use https

---

config/environment.rb
config/routes.rb

We're adding PasswordPusher to the Slack application directory.
These are the additions required to support this.
With these changes, users can point their own slack app integrations to their own instances of PasswordPusher as well.

Slack App Directory Support

---

app/assets/stylesheets/passwords.css.scss
app/views/passwords/show.html.haml

I think there were a misunderstanding on Issue #52, "Copy to clipboard" button on first password view is to copy link of the password, not the password itself. I think @todd-a-jacobs thought about adding a "Copy to Clipboard" button but for the password, which I did in this PR.
- ✨ Add button to copy password to the clipboard without revealing it, increasing safety of the password against lookup upon user's shoulder.
#52
NO

feat(PasswordsView): add button to copy password in clipboard

---

app/views/passwords/new.html.haml

When selecting a number of days/views on the password creation page, the number displayed in the UI only updates when the slider is released. I think it would be easier to select a precise number of days/views if the UI updates as the slider moves.
I left the `change` handlers because IE8 and earlier don't support the `input` event - maybe it isn't necessary to try and support those browsers.

Update number of days/views as slider is moved

---

app/controllers/passwords_controller.rb
app/models/password.rb
test/integration/password_creation_test.rb
test/integration/password_json_creation_test.rb
test/integration/password_json_deletion_test.rb
test/integration/password_json_retrieval_test.rb

This PR adds:
* JSON POST requests now return the original password in the JSON body
(instead of the encrypted version which was useless)
* All JSON response bodies now include `days_remaining` and
`views_remaining`
```
{
"id": 13,
"payload": "mypassword", # <----------------
"expire_after_days": 2,
"expire_after_views": 10,
"expired": false,
"url_token": "vqz3wty1ygt8yc2u",
"created_at": "2020-07-27T09:31:25.256Z",
"updated_at": "2020-07-27T09:32:48.002Z",
"user_id": null,
"deleted": false,
"first_view": false,
"deletable_by_viewer": false,
"days_remaining": 2, # <----------------
"views_remaining": 6 # <----------------
}
```
This fixes #119 although I'm not going to utilize `updated_at` right now because eventually I want to expose the list of views in the UI which will show when they …

JSON API: Add original payload and days/views remaining

---

app/controllers/commands_controller.rb
config/initializers/cookies_serializer.rb

Changing serializer to :json will prevent Remote Code Execution exploiting marshals serializer vulnerability.
render: text => @password.errors may lead to Cross Site Scripting (found by Brakeman). Using render :simple will prevent it.

Fixing RCE and XSS vuln

---

config/initializers/cookies_serializer.rb

The original value of `Rails.application.config.action_dispatch.cookies_serializer` was `:marshal`.  Updating this setting to `:json` caused application errors triggered by failed cookie deserialization for returning users.
This change was originally initiated from https://github.com/pglombardo/PasswordPusher/pull/147 in response to warning from [brakeman](https://github.com/presidentbeef/brakeman).
But after some investigation it seems which CVE this addresses isn't even clear - it seems that the threat is theoretical: https://github.com/presidentbeef/brakeman/issues/1316
We could just invalidate all pre-existing user cookies by changing the secret key base, but this would require every person running a self-hosted version of PasswordPusher to perform this manual task (which is a hassle …

Use :hybrid cookie serialization

---

app/controllers/commands_controller.rb

Fixes #142 - slack integration bug
Upgrade commands controller to use `render :plain` as opposed to the deprecated `render :text`. 
According to the rails changelog, `render :text` was deprecated in rails 5.1
https://github.com/rails/rails/blob/v5.1.0.rc1/actionpack/CHANGELOG.md
Using `render :plain` has been available for sometime, and is now the required way of rendering `text/plain`
https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-text

Update commands controller for rails 5.2

---

app/controllers/passwords_controller.rb
app/views/passwords/show.html.haml

This still needs testing across platforms and clouds.
If you set the environment variable `FORCE_SSL=true`, it will enable `config.force_ssl=true` AND force the password show page to use an `https` URL for the password.  This happens even if you are not running an SSL server and nothing on port 443.
I'll update with what I find after testing a bit.

Force SSL URLs

---

README.md

I built a small Android app that uses pwpush.com.
I've added it to the README in case you was interested in checking it out.

Add Android app link to README

---

Gemfile
Gemfile.lock
app/models/password.rb
test/integration/password_creation_test.rb
test/integration/password_json_creation_test.rb

As reported in #204, JSON encoding is choking on certain characters.  To resolve we switch the Oj gem which has better semantics/handling and also gives us a performance boost.
Fixes #204

Fix JSON encoding of uncommon characters

---

db/migrate/20210913083515_add_note_to_password.rb

This default value breaks MySQL and is entirely unnecessary.
Fixes #245

Migrations: Remove default value for note

---

Configuration.md
Gemfile
Gemfile.lock
app.json
app/controllers/passwords_controller.rb
app/models/password.rb
app/views/pages/generate_key.html.erb
app/views/shared/_footer.html.erb
config/environment.rb
config/initializers/lockbox.rb
config/initializers/secret_token.rb
db/migrate/20211104102822_add_payload_ciphertext_to_password.rb
db/schema.rb

Password Pusher has been using ezcrypto which has worked well but it is a bit aged and untouched for quite a while.
The new strategy will use [lockbox and its AES-GCM](https://github.com/ankane/lockbox#aes-gcm) algorithm.
Lockbox also provides a tighter integration which means simpler code for pwpush.
The migration strategy is simple in that we start using the new encryption strategy for all new pushes.  For legacy pushes (which live a maximum of 90 days), just fall back to the legacy strategy.
Eventually (after 3 months or longer), I'll remove the legacy ezcrypto strategy entirely.

Updated Encryption Strategy with Lockbox

---

containers/docker/pwpush-mysql/entrypoint.sh
containers/docker/pwpush-postgres/entrypoint.sh

Launch the container puma process directly to avoid the recent port
increment issues with the foreman utility.
Fixed #261

Remove Foreman from Containers

---

app/controllers/commands_controller.rb
app/controllers/passwords_controller.rb

Initiated from #251 and #48, this PR switches to `SecureRandom` for token generation with a random (8..14) token length.
This increases the complexity of guessing tokens.  Combined with the installed rate limiter and short expiration dates, the risk is further limited.
In the extreme case where a token may be guessed, make sure to push passwords only.  Don't include what they go to.

SecureRandom: Better URL token generation

---

README.md
config/initializers/translation.rb
config/routes.rb
config/settings.yml

Fixes #267 
Password Pusher supports 13 languages that is selectable by an in-app menu.  The default language is English (until a language menu item is selected).
This PR adds the `PWP__DEFAULT_LOCALE` environment variable to override the default language.
Instructions added to the front [README page](https://github.com/pglombardo/PasswordPusher/tree/master#internationalization).
For example, setting the following environment variable for the application will make Spanish the default language for the application:
PWP__DEFAULT_LOCALE=es

Allow for the Default Language to be changed

---

containers/docker/pwpush-mysql/Dockerfile

The pwpush-mysql Docker image is hitting a [bootsnap bug](https://github.com/Shopify/bootsnap/issues/378) with Ruby 3.0.3.  We'll downgrade to Ruby 3.0.2 until the issue is resolved.

Use Ruby 3.0.2 to avoid bootsnap bug

---

app/controllers/passwords_controller.rb

Protect against things that aren't strings

---

containers/docker/pwpush-mysql/docker-compose.yaml

Fixes #368 
https://hub.docker.com/_/mariadb

pwpush-mysql: Update to default Mariadb data path

---

Configuration.md
config/settings.yml

The inserted environment variable did not conform to the
option in the settings file.  This should fix the issue
of not having the footer be hidden when setting the value
to false.

fix(settings): variable name did not reflect parameter

---

containers/docker/pwpush-ephemeral/Dockerfile
containers/docker/pwpush-mysql/Dockerfile
containers/docker/pwpush-openshift/Dockerfile
containers/docker/pwpush-postgres/Dockerfile

Move Docker images to slim base images

---

config/environments/development.rb
config/environments/private.rb
config/environments/production.rb
config/settings.yml

Fixed #385 
To disable SSL cert verification, you can set `PWP__MAIL__SMTP_OPENSSL_VERIFY_MODE='none'` or modify and overlay `config/settings.yml`

SMTP: Add extended config options

---

Gemfile
Gemfile.lock
gemfiles/Gemfile-mysql
gemfiles/Gemfile-mysql.lock

Fixed #397
https://github.com/rails/rails/pull/44083
https://stackoverflow.com/questions/70500220/rails-7-ruby-3-1-loaderror-cannot-load-such-file-net-smtp

Fix: Workaround for Rails 6 + Ruby 3.1 bug

---

containers/docker/pwpush-ephemeral/Dockerfile
containers/docker/pwpush-mysql/Dockerfile
containers/docker/pwpush-postgres/Dockerfile

Version limit the docker containers because nokogiri doesn't yet support
v3.2.
From [this action](https://github.com/pglombardo/PasswordPusher/actions/runs/3790398090/jobs/6445312306):
```
#18 6.627 nokogiri-1.13.10-x86_64-linux requires ruby version < 3.2.dev, >= 2.6, which is
#18 6.627 incompatible with the current version, 3.2.0
```

Version limit Docker containers to Ruby 3.1

---

containers/docker/pwpush-ephemeral/Dockerfile
containers/docker/pwpush-mysql/Dockerfile
containers/docker/pwpush-openshift/Dockerfile
containers/docker/pwpush-postgres/Dockerfile

Reverts pglombardo/PasswordPusher#649
Node.js is required for asset compilation.  Using a gem based v8 engine is more trouble than it's worth.  Reverting this change.

Revert "Remove Node.js and Yarn from Docker containers"

---

config/initializers/devise.rb

Registration with Turbo streams seems to be broken.
Known issue with devise: https://github.com/heartcombo/devise/issues/5439
- Latest language strings
- Fix registration

Fix: Registration + Turbo Streams

---

.github/workflows/docker-containers.yml

This has proven to break pulling images with older clients.
https://github.com/docker/buildx/releases/tag/v0.10.0
Read a bit more: https://github.com/docker/buildx/issues/1533
With the recent release of buildx 0.10.0 things has started to break.  This is caused by something called provenance and in turn has caused problems when pulling the images because changes to the mediatype metadata.
```
$ docker buildx imagetools inspect pglombardo/pwpush-ephemeral:1.24.4
Name:      docker.io/pglombardo/pwpush-ephemeral:1.24.4
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:76c9535b5219457549e549fa24c415678ef37c55a5199593ddd41a497bbf0384
Manifests: 
Name:      docker.io/pglombardo/pwpush-ephemeral:1.24.4@sha256:fa63f204749695122df7c2f64270a4120480b7a83d9af10f604 …
```

ci: disable provenance when building images

---

app/views/layouts/_ga.html.erb

Turbolinks doesn't allow GA to track subsequent page loads.
Update the code with a turbolinks listener.
[source](https://dev.to/tylerlwsmith/using-google-analyticss-gtagjs-with-turbolinks-5coa)

GA: Add Turbolinks support

---

config/defaults/settings.yml
config/settings.yml
containers/docker/pwpush-ephemeral/entrypoint.sh
containers/docker/pwpush-mysql/entrypoint.sh
containers/docker/pwpush-postgres/entrypoint.sh

Docker: Don't Precompile Assets by Default
Set the environment variable `PWP_PRECOMPILE` if you want assets to be precompiled on container boot.
This is useful for people who add custom CSS, images or JS.

Docker: Don't Precompile Assets by Default

---

app/assets/stylesheets/application.scss.erb

Custom CSS wasn't getting loaded last because of odd behaviour with Sass CSS imports.
Fixes #931
#931

Custom CSS: Use different import style for proper ordering

---

README.md

A user just suggest to add your app to [PikaPods](https://www.pikapods.com/apps#new). Been looking for something similar for a while and it looked solid. So complied right away.
Preview: https://github.com/m3nu/PasswordPusher/tree/add-pikapods#on-pikapods
About PikaPods: We aim to make great open source apps, like PasswordPusher more accessible and easier to get started with. Currently we offer around 60 different apps that can be deployed with a single click and managed in a simple control panel.
So I'm suggesting to add PikaPods as additional deployment option. This would help an even wider audience to benefit from the project and run their own. We also do revenue sharing with our authors, which may be of interest in the future.
Thanks for the consideration!

Add PikaPods deployment option

---

config/initializers/route_translator.rb

This fixes a deprecation warning in route_translator.
Details on the deprecation are here:
https://github.com/enriclluelles/route_translator/pull/285
The original deprecation warning.
```sh
DEPRECATION WARNING: `i18n_use_slash_separator` set to `false` is deprecated and will be
removed in the next major release of Route Translator to match
Rails' ActiveRecord nested model syntax.
More information at https://github.com/enriclluelles/route_translator/pull/285
```

Set i18n_use_slash_separator=true

---

app/controllers/urls_controller.rb

This fixes an issue where URL pushes with the 1-click option incorrectly required the user to login.
Reported via feedback from a end user.

Fix URL push 1-click option

---

.github/workflows/docker-containers.yml

Change to use the upstream [Docker Metadata action](https://github.com/marketplace/actions/docker-metadata-action) for populating the tags.  The old action is obsolete.
I've commented out the workflow_dispatch section as to ask how it's used in the real world.  Is it something that we can tweak using the upstream action?
Ed1t: my goal was to have these in the image:
```json
"Labels": {
"maintainer": "pglombardo@hey.com",
"org.opencontainers.image.created": "2023-06-27T17:27:21.882Z",
"org.opencontainers.image.description": "🔐   An application to securely communicate passwords over the web.  Passwords automatically expire after a certain number of views and/or time has passed.  Track who, what and when.",
"org.opencontainers.image.licenses": "Apache-2.0", …
```

Change to use docker metadata action for tags

---

app/controllers/file_pushes_controller.rb
config/environments/development.rb
config/environments/private.rb
config/environments/production.rb

This fixes the following issues: 
* When this was a create error, it would then hit a second error.
* When using `PWP__OVERRIDE_BASE_URL`, we now add it to the list of allowed hosts

Improve Override URL: Add host to allowed domains

---

config/defaults/settings.yml
config/environments/development.rb
config/environments/private.rb
config/environments/production.rb
config/settings.yml

This adds a new option to the Settings object `allowed_hosts`.
This configured which Host Headers the application is authorized to respond to.
Documentation in the `settings.yml`
Fixes #1343

Add optional allowed_hosts setting

---

config/defaults/settings.yml
config/settings.yml

Increase the default throttling thresholds.
This is useful when people apply site monitors that ping the site often.
Fixes #1107

Throttling: Increase default thresholds

---

Gemfile
Gemfile.lock

The latest bootstrap gem update breaks the dark theme on pwpush.com.   Until I update the theme to follow recent bootstrap changes we will limit the bootstrap gem to 5.2.3.

Fix: Dark theme regression with updated Bootstrap

---

config/defaults/settings.yml
config/settings.yml

This PR increases the default throttle limits.
It was found that for file uploads, the per second throttling limits were being hit.

Fix: Increase default throttle limits

---

.github/workflows/docker-containers.yml

This PR reenables the option to use workflow dispatch for `build` action.
It's now allowed to run workflow dispatch at anytime with or without pushing to docker hub.
In current state the tag for the image is set by its commits SHA.
Additionally due to caching and if using in an fork it's necessary to have:
- `secrets.DOCKER_USERNAME` set according to docker hub account. 
(if not pushing pushing to docker hub it only needs some random value)
- `secrets.DOCKER_PASSWORD` set according to docker hub account. 
https://github.com/pglombardo/PasswordPusher/pull/1369#issuecomment-1713656580

Changes to enable workflow dispatch for 'build' github action

---

Gemfile.lock
containers/docker/pwpush/Dockerfile

Working #1509 was a bit too slow when the layers were in the old order.  `COPY ./ .` early in will result to always needing to build the deps.
Even updated `Gemfile.lock` to the version inside the container, again to limit the need for rebuild.
And, do we really need `ENV LC_CTYPE=UTF-8 LC_ALL=en_US.UTF-8`?  I see no docs on why.  Upstream already sets UTF-8 https://github.com/docker-library/ruby/blob/31c1fdba369192fe2c3cf327d7d98819edc1400b/3.2/alpine3.18/Dockerfile#L28
Ed1t: I also put the packages on separate lines so it's easier to see what is installed.  I personally prefer this as a way to always have control what is installed.  That way you can look for similarities, etc. for improving the container images.

refactor(dockerfile): move layers around for speed improvement

---

config/defaults/settings.yml
config/settings.yml

Revise the application's language menu by replacing the "zh-CN" label with '中文' to avoid confusion. 
中国人 - Refers to people from China or of Chinese descent.
中文 - Refers to the Chinese language.

Revise zh-CN label in application language menu

---

containers/docker/pwpush-postgres/docker-compose.yml
containers/docker/pwpush/docker-compose-postgres.yml
containers/kubernetes/persistent_deploy.yaml

This updates the postgres version to 15 in the container files.
pwpush.com is running v15 without issue.
Pointed out in issue #1622

Update postgres version to 15

---

.dockerignore
.github/workflows/ruby-tests.yml
Gemfile
Gemfile.lock
README.md
containers/docker/pwpush/Dockerfile

This PR:
1) Switches back to the prebuild `simple_token_authentication` gem. 
Rails 7 support got merged on upstream. No further reason to use forked version. 
2) Database groups `sqlite`, `mysql2` and `postgres` seem to obsolete due the #1369.
Removed and fix locations where they where used.

Use prebuild 'simple_token_authentication' gem and remove database backend groups in Gemfile

---

Configuration.md
app/views/file_pushes/active.html.erb
app/views/file_pushes/audit.html.erb
app/views/file_pushes/expired.html.erb
app/views/passwords/active.html.erb
app/views/passwords/audit.html.erb
app/views/passwords/expired.html.erb
app/views/urls/active.html.erb
app/views/urls/audit.html.erb
app/views/urls/expired.html.erb
config/defaults/settings.yml
config/settings.yml

This add a new option to the `settings.yml` to set the application wide
timezone.
Modify that file or set `PWP__TIMEZONE` to a valid timezone string.  The list of valid
timezone strings can be found here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#345

Timezones: Add option to set application default Timezone

---

containers/docker/pwpush-ephemeral/Dockerfile
containers/docker/pwpush-mysql/Dockerfile
containers/docker/pwpush-postgres/Dockerfile

This PR replaces the deprecation notice introduced in #1369 into a end-of-support notice.
This is in preparation to #1555 and ment to inform users to migrate as soon as possible.

DOCKER: Insert end-of-support notice into obsolete docker images

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb

Add Memory Profiler to fix memory leak

---

app/controllers/application_controller.rb

This was breaking requests in 1.36.1

Remove MiniProfiler call

---

containers/docker/Dockerfile

Ruby 3.3 has a bug with alpine that is breaking the container builds.   We'll update after 3.3.1 is released with the fix.
Reverts pglombardo/PasswordPusher#1757
Revert until the Ruby 3.3 segfault on asset:precompile bug is fixed in 3.3.1.

Revert "Bump ruby from 3.2-alpine to 3.3-alpine in /containers/docker"

---

app/assets/stylesheets/application.scss.erb
app/views/layouts/application.html.erb
app/views/layouts/bare.html.erb
app/views/layouts/login.html.erb
app/views/layouts/naked.html.erb
config/initializers/assets.rb
package.json
yarn.lock

flag-icons and boostrap-icons are currently loaded via CDN.  This PR moves these assets locally so no external requests are needed for the application to function.
#1735

GDPR: Host Assets Locally

---

containers/docker/Dockerfile

With recent changes in #1828 & #1827, we no load assets from the node_modules directory.
Previously this directory was deleted to reduce image size but unfortunately that is not an option going forward.

Keep node_modules in Docker image

---

Gemfile.lock

We do this to not trigger a rebuild of layers.
> 37.02 Bundler 2.4.19 is running, but your lockfile was generated with 2.4.10. Installing Bundler 2.4.10 and restarting using that version.

fix: bump bundler version in lockfile

---

.gitignore
config/defaults/settings.yml
config/environments/production.rb
config/initializers/rack_attack.rb
config/settings.yml

Docker container logging broke with some update recently.  This PR fixes the logging.
Use your `settings.yml` to set logging options.  By default, the logger will log to `/opt/PasswordPusher/log/production.log` at a `warn` level.
So it should just be warnings and errors if there are any.
This should hopefully assist in debugging and finding error details.

Fix Container Logging

---

config/defaults/settings.yml
config/initializers/translation.rb
config/settings.yml

This fixes #1904.
To disable a language, remove it from the `enabled_language_codes` list in the `settings.yml`

Add "enabled_language_codes" option

---

config/database.yml

The Docker container sets [DATABASE_URL=sqlite3:db/db.sqlite3](https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/Dockerfile#L43) but the application config file sets `db/production.sqlite3` in config/database.yml.  This doesn't break anything but when you open a console in Docker, the discrepancy causes issues such as #1991.
So for production environment and not using a postgres or mysql database, `db/db.sqlite3` it is.

Config: Make default db db/db.sqlite3

---

app/controllers/file_pushes_controller.rb
app/controllers/passwords_controller.rb
app/controllers/urls_controller.rb

```
Unpermitted parameters: :locale, :id. Context: { controller: PasswordsController, action: print_preview, request: #<ActionDispatch::Request:0x000000011429d848>, params: {"message"=>"", "show_expiration"=>"true", "show_id"=>"true", "locale"=>"en", "controller"=>"passwords", "action"=>"print_preview", "id"=>"w2ctlqogpcg5byg"} }
```

QR Code Print: Add More Allowed Params

---

README.md
containers/docker/all-in-one/Caddyfile
containers/docker/all-in-one/README.md
containers/docker/all-in-one/docker-compose-pwpush.yml

The files in this directory allow you to launch a Password Pusher instance with automatic SSL/TLS certificate management thanks to Caddy server & Let's Encrypt.
tldr; Launch and get Password Pusher hosted with valid SSL certs for the domain you specify.

Launch Password Pusher with Let's Encrypt SSL/TLS Certificates

---

app/controllers/users/confirmations_controller.rb
app/views/devise/confirmations/show.html.erb
config/locales/pwpush.en.yml

To address the issues raised in #2180, this PR adds a required click through to confirm accounts.
#2180

User Confirmation: Add click-through step

---

containers/helm/templates/deployment.yaml

Currently the helm chart does not set a podSecurityContext. This may prevent the use in kubernetes clusters which do not allow images that run as root for security reasons.
The Container already uses a non root user, so setting runAsNonRoot and specifying the User/Group ID (because runAsNonRoot requires a numeric user for validation) is sufficient. This allows the use in kubernetes clusters which do not allow images running as root.
- [x ] 🥂 Improvement (non-breaking change which improves an existing feature)

Adjust helm chart to runAsNonRoot

---

Configuration.md
Gemfile
Gemfile.lock
config/defaults/settings.yml
config/initializers/rack_attack.rb
config/settings.yml

We've historically been using [rack-throttle](https://github.com/dryruby/rack-throttle) for request throttling.  That gem has been deprecated in favor of [rack-attack](https://github.com/rack/rack-attack) which this PR switches us to.
The change-over should be transparent for end users.

Switch to Rack::Attack for Throttling

---

config/environments/production.rb

This left over bit was breaking the Docker builds.

Remove last bit of Rack::Throttle

---

config/routes/legacy_pushes.rb

Language codes with capitalization (such as `pt-BR`) were not redirecting properly.

Downcase language codes

---

config/defaults/settings.yml
config/settings.yml

For those running local mailservers (e.g. localhost:25), the `smtp_authentication` should be nil.
Fixes #2360

Email: Authentication nil by default

---

config/defaults/settings.yml
config/settings.yml

Correct the environment variable for the syllables_count value.
None

Fix environment variables in comments for syllables_count

---

config/puma.rb

A recent commit changed the calculation of the number of puma workers to boot.  It was based on CPU count which in some cases would launch 10+ workers.
This is unnecessary.  pwpush.com and it's high traffic volume is handled with just 3 workers.
A default of 2 workers is more than sufficient for self-hosted instances.
If you need to increase the number of workers, set the environment variable `WEB_CONCURRENCY` to the number of desired workers.

Fix Workers Count: Set default count of 2

---

app/mailers/test_mailer.rb

The TestMailer wasn't correcting validating configuration for local unauthenticated mail servers.
#2471

Fix: Better TestMailer with checks for local mail server.

---

app/controllers/file_pushes_controller.rb
app/controllers/passwords_controller.rb
app/controllers/urls_controller.rb
app/views/devise/registrations/new.html.erb
app/views/file_pushes/show.html.erb
app/views/passwords/show.html.erb
config/routes.rb

- **Simplify expire checks and response**
- **Only show delete button if any views remain**
- **Gateway: define a root path**
#2522

Fix: Deleting Push with Last View yields Error 500

---

app/models/user.rb
config/initializers/devise.rb

This PR improves the security of logins.  
If you're not using logins in your Password Pusher instance, this PR won't apply to you.
Changes:
1. Confirmation, password recovery and other workflows will now behave the same regardless if the e-mail provided was right or wrong.  This avoids confirming whether an account exists or not in the system.
2. Account confirmations must now be done within 3 days otherwise the user will have to request a new confirmation token.
3. User sessions now timeout in 30 minutes of no activity.  Being a security product with sensitive data, this is appropriate.

Enable increased login security

---

app/views/shared/_header.html.erb

For users that are marked as administrators, new admin menu item for easier access.

Admin: Add admin dashboard to account menu

---

Gemfile
config/initializers/rack_attack.rb

This PR fixes #2684 and enables login brute force protections:
* Throttle POST requests to `/users/sign_in` by email param
* Limit POST requests to `/users/sign_in` to 5 per 20 seconds
These changes also mean that you can now disable throttling entirely by commenting out the `throttling.minute` and `throttling.second` values in `settings.yml`.
#2684

Throttling fix & Add protection against login brute forcing

---

app/controllers/users/registrations_controller.rb
config/routes/users.rb

Reported by a user via email who was using `PWP__ALLOW_ANONYMOUS=false`:
```
"after creating an account it doesnt show the pop up which tells 
me to verify my e-mail. It rather shows the same pop up which 
can be confusing for the end user.
```
This PR changes the after sign up path when account confirmation is required (pretty much always).
Now after sign up when `PWP__ALLOW_ANONYMOUS=false`, you get this:

Allow Anonymous=false: Fix after sign up redirect path

---

config/defaults/settings.yml
config/environments/development.rb
config/environments/production.rb
config/settings.yml

This PR adds a rule to only trust proxies on the local network.
This fixes a weakness where the `X-Forwarded-For` header could be spoofed by unauthorized clients to bypass the rate limiter.
This can be overridden by the new `trusted_proxies` setting:
```yaml
#
#
#
#
```

Security: Only trust local proxies unless overidden

---

app/controllers/file_pushes_controller.rb
app/controllers/passwords_controller.rb
app/controllers/urls_controller.rb

Increase passphrase cookie storage:
* Only send the cookie over HTTPS in production
* Prevent JavaScript access to the cookie
* Restrict the cookie to same-site requests

Passphrase: Increase cookie security

---

config/initializers/devise.rb

If a user has 10 failed login attempts the account is locked and an email is sent to the email address for the account.
From the sent email, the user can unlock his/her account.
This PR lowers the failed attempts from 20 to 10.
#2798

Login: Lock accounts after 10 failed attempts

---

containers/docker/docker-compose-mariadb.yml
containers/docker/docker-compose-mysql.yml

This pull request addresses issues in the `docker-compose-mysql.yml` and `docker-compose-mariadb.yml` files related to the naming of the database services. Currently, both the MySQL and MariaDB containers have inconsistent service names. The MySQL container is defined under the service name `db`, while the application container attempts to connect to it using the name `mysql`. Similarly, the MariaDB container is also misconfigured. These discrepancies can lead to connection issues, particularly when the stack is integrated into a more complex environment, such as when the container is behind a reverse proxy. Using the correct service names is also a cleaner and more maintainable approach, regardless of the environment in which the stack is deployed.
After making these changes, I ran the …

fix database service names in docker-compose-xx.yml

---

app/views/file_pushes/preliminary.html.erb
app/views/passwords/preliminary.html.erb
app/views/urls/preliminary.html.erb

This is the second attempt to block browser pre-fetching.  This time by adding `rel="no-prefetch"` to the "Click here to proceed link".
#2225

Preliminary: Set rel="no-prefetch" to block browser pre-fetch

---

config/defaults/settings.yml
config/initializers/cloudflare_proxy.rb
config/settings.yml

With recent releases only local proxies are trusted by default.  There is a [setting](https://github.com/pglombardo/PasswordPusher/blob/master/config/settings.yml#L698-L715) that allows you to add IPs to this list but in cases where Cloudflare has a long list or often change IPs this can be troublesome.
This PR adds `PWP__CLOUDFLARE_PROXY=false` and a `cloudflare_proxy: false` in your `settings.yml`.  Set one of these to `true` to enable fetching of CloudFlare IPs on container boot.
See #2799 for the discussion.
#2799

New Cloudflare Setting: Optionally fetch CF IPs on container boot.

---

set_theme.js

The new theme selection doesn't downcase the name to match the filename.  Fixed.
#2905

Fix: Downcase theme selection

---

containers/docker/Dockerfile

Things that previously built without issue are now failing.  I believe this is due to a base layer change.
```
#16 1967.5 current directory:
#16 1967.5 /opt/PasswordPusher/vendor/bundle/ruby/3.4.0/gems/puma-6.6.0/ext/puma_http11
#16 1967.5 /usr/local/bin/ruby extconf.rb
#16 1967.5 checking for pkg-config for openssl... *** extconf.rb failed ***
#16 1967.5 Could not create Makefile due to some reason, probably lack of necessary
#16 1967.5 libraries and/or headers.  Check the mkmf.log file for more details.  You may
#16 1967.5 need configuration options.
```
This PR adds openssl-dev.

Fix: Continued Alpine Adjustments

---

app/javascript/application.js
app/views/layouts/application.html.erb

Adds support for a new environment variable `TURBO_DRIVE_ENABLED` documented here: https://docs.pwpush.com/docs/self-hosted-configuration/

Add environment variable to disable Turbo Drive

---

config/defaults/settings.yml
config/initializers/devise.rb
config/settings.yml

In `settings.yml`:
```
#
#
#
#
#
#
```

New Login Session Timeout Config Option

---

app/views/devise/confirmations/show.html.erb
app/views/file_pushes/show.html.erb
app/views/layouts/login.html.erb
app/views/passwords/show.html.erb

This PR fixes a bunch of problems across many themes related to dark mode.
Also, push delivery pages now show up in Dark mode.  😎

Fix Dark Themes: Remove forced bg-light

---

app/controllers/api/base_controller.rb
app/controllers/api/v1/version_controller.rb
config/initializers/apipie.rb
config/routes.rb
config/routes/pwp_api.rb
test/fixtures/users.yml
test/integration/api/api_version_test.rb
test/test_helper.rb

This PR adds a new API call to the JSON API: 
GET `/api/v1/version` will return version information about the instance in use.
This will be updated to include additional information very soon.

JSON API: New Version Endpoint

---

containers/docker/entrypoint.sh

Previously, I introduced the `pwpush-worker` container but haven't brought it past Beta.
This PR is a different approach to simply run the background worker in the same `pglombardo/pwpush` container.
If this change goes well, I may scrap the `pwpush-worker` container.
Running in the single container is just simpler.

Run Background Worker in Core Container

---

app/assets/stylesheets/themes/selected.css

This file is generated on application boot by `set_theme.js`.  It's not necessary to have it in version control.

Themes: Remove selected.css; generated on boot

---

package.json

Yarn official page is recommending to use yarn with corepack. When corepack is installed and run `yarn install` it is adding yarn version into `package.json`. It allows to use correct yarn version locally. 
-
Any test is not added. So, I'm skipping this part.
@pglombardo

Add the yarn version used by corepack

---

config/environments/development.rb

With #3342, the host used for emails sent/shown emails is removed mistakenly. It prevents to send emails locally.
So, a default host is added.
#3342 
-- I haven't added any test

Add a default host for emails sent/shown locally

---

app/controllers/api/v1/file_pushes_controller.rb
app/controllers/api/v1/passwords_controller.rb
app/controllers/api/v1/urls_controller.rb
app/controllers/file_pushes_controller.rb
app/controllers/passwords_controller.rb
app/controllers/urls_controller.rb
app/models/file_push.rb
app/models/password.rb
app/models/url.rb
app/views/file_pushes/active.html.erb
app/views/file_pushes/new.html.erb
app/views/passwords/active.html.erb
app/views/passwords/new.html.erb
app/views/urls/active.html.erb
app/views/urls/new.html.erb
config/locales/pwpx.en.yml
db/migrate/20250513074136_add_name_to_models.rb
db/schema.rb
test/integration/file_push/file_push_active_test.rb
test/integration/file_push/file_push_json_creation_test.rb
test/integration/password/password_active_test.rb
test/integration/password/password_json_creation_test.rb
test/integration/url/url_active_test.rb
test/integration/url/url_json_creation_test.rb
test/models/file_push_test.rb
test/models/password_test.rb
test/models/url_test.rb
test/unit/password_test.rb
test/unit/password_unit_test.rb

"name" attribute is added into `Url`, `Password` and `FilePush` models. Also, related views and API endpoints are updated. Tests are added, too.
#3336

Add `name` to pushes

---

.github/workflows/ruby-tests.yml
app/javascript/controllers/knobs_controller.js
app/views/file_pushes/new.html.erb
app/views/passwords/new.html.erb
app/views/urls/new.html.erb
test/application_system_test_case.rb
test/system/file_push_cookies_test.rb
test/system/file_pushes_test.rb
test/system/password_cookies_test.rb
test/system/url_cookies_test.rb
test/system/urls_test.rb

Saving settings was available for only the passwords tab, not for files and Urls tabs. "Save" buttons are added into tabs to save settings. Each tab can store settings separately.
Tabs with saved settings;
Tabs without saved settings(all tabs are same);
#3352 
-- There is no info to add into documents

Add a "Save" button into two tabs

---

db/migrate/20250515110051_remove_text_from_urls_and_file_pushes.rb
db/schema.rb

`text` columns were added mistakenly. They are not used actively and contain any data. So, they removed.
#3357 
-- Changes don't need to be tested.
-- Changes don't need to be documented..

Remove unused text columns from urls and file_pushes tables

---

app/jobs/migrate_data_to_push_model_job.rb

The logger used by MigrateDataToPushModelJob is the default logger of Rails. But, MigrateDataToPushModelJob has some `info` logs but the default logger's level is `warn` and `info` logs won't be shown in the logger. So, a new logger is added to this job.
--
-- No need to add/update tests
-- No need to add/update documentation

Update the logger used by MigrateDataToPushModelJob

---

yarn.lock

This PR fixes the above CVE ([GO-2025-3563](https://pkg.go.dev/vuln/GO-2025-3563)) that was in an older version of esbuild.

CVE-2025-22871: Update to resolve

---

db/migrate/20250515121325_create_pushes.rb
db/migrate/20250515193130_create_audit_log.rb

User reported a integer type mismatch on db migration in #3422.
#3422

Push Create: Add fix for MariaDB id type conflict

---

Gemfile
Gemfile.lock
config/application.rb
test/integration/admin_dashboard_test.rb

A stylesheet used by mission_control-jobs is loaded by using CDN. This isn't acceptable by GDPR. [This issue fixed by gem contributors](https://github.com/rails/mission_control-jobs/commit/d43649cdddace2ec5ab2236f74ef41f06f4bc21d) with the latest version. So, the gem is upgraded.
#3460
-- No need to document

Update the version of the mission_control-jobs gem

---

app/views/pushes/_push.json.jbuilder
test/integration/file_push/file_push_json_active_test.rb
test/integration/file_push/file_push_json_expired_test.rb
test/integration/password/password_json_active_test.rb
test/integration/password/password_json_expired_test.rb

#3395 API responses are updated. But, `note` and `name` fields are removed from API responses of `active` and `expired` pushes mistakenly. So, it is updated to return these fields in these responses.
#3508
-- No need to document

Add fields to API responses of active and expired pushes

---

db/migrate/20250606094103_drop_legacy_models.rb

```
ActiveRecord::Base.connection.execute(<<-SQL).first
SELECT (
(SELECT COUNT(*) FROM passwords) +
(SELECT COUNT(*) FROM urls) +
(SELECT COUNT(*) FROM file_pushes)
) as total_count
SQL
```
is returning `[0]` for MySQL2 and  `{"total_count" => 0}` for SQLite3 and PostgreSQL. So, it is causing an error.
It is fixed to return `0`;
```
ActiveRecord::Base.connection.select_value(<<-SQL)
SELECT (
(SELECT COUNT(*) FROM passwords) +
(SELECT COUNT(*) FROM urls) +
(SELECT COUNT(*) FROM file_pushes)
)
SQL
```
What is the problem?
[SQLite2 returns result of high-level queries in a hash](https://github.com/brianmario/mysql2/tree/441b104f8f120788e86086702d96963aecec3172?tab=readme-ov-file#array-of-hashes). So, it doesn't cause any issue when working with ActiveRecord. But, the result of lower-level …

Fix a raw SQL for MySQL2

---

containers/docker/Dockerfile
containers/docker/Dockerfile.public-gateway
containers/docker/Dockerfile.worker

This PR fixes the container image by properly including the `entrypoint.sh` script, which was previously missing from the image filesystem.
**✅ Changes made:**
- Added containers/docker/entrypoint.sh to the image using COPY.
- Set the correct ENTRYPOINT path to /usr/local/bin/entrypoint.sh.
- Ensured the script has executable permissions.
This change ensures the container can start properly, avoiding the following runtime error:
> OCI runtime create failed: runc create failed: unable to start container process: exec: "containers/docker/entrypoint.sh": stat containers/docker/entrypoint.sh: no such file or directory: unknown
Let me know if you prefer a more concise or formal tone.

🛠 Fix image entrypoint path

---

app/jobs/expire_pushes_job.rb

Fixed log message of ExpirePushesJob Job regarding the number of deleted pushes.
Fixes https://github.com/pglombardo/PasswordPusher/issues/3644

Fix: use expiration_count variable
