pglombardo/PasswordPusher

app/assets/stylesheets/passwords.css.scss, app/views/passwords/show.html.haml
From this twitter discussion: https://twitter.com/mythofechelon/status/897782049775529984
=> Better Language (per Request)

app/controllers/passwords_controller.rb
=> JSON API: Make raw password available in JSON responses

app/controllers/passwords_controller.rb
Reported in #110, this adds detection of the `first_view` in POST payload.
=> Detect and use `first_view` if in POST payload

app/views/layouts/application.html.haml, app/views/passwords/new.html.haml
...only show on front page and specifically not on password pages.
=> Fork Me: Only show on the front page

.gitignore, Gemfile, app/assets/stylesheets/global.css.scss, app/assets/stylesheets/passwords.css.scss, app/views/layouts/application.html.haml, app/views/pages/about.html.haml, app/views/pages/faq.html.haml, app/views/passwords/new.html.haml, app/views/passwords/show.html.haml, test/integration/password_creation_test.rb, test/test_helper.rb
This PR makes some tweaks and updates that allow better visibility on small screens.
End result:
=> Mobile: Update site to be responsive

app/assets/javascripts/passwords.js, app/assets/stylesheets/passwords.css.scss, app/views/passwords/show.html.haml
Closes https://github.com/pglombardo/PasswordPusher/pull/148
Closes https://github.com/pglombardo/PasswordPusher/issues/145
=> Fix Secret URL copy to clipboard

app/controllers/passwords_controller.rb, test/integration/password_json_creation_test.rb, test/integration/password_json_deletion_test.rb, test/integration/password_json_retrieval_test.rb
=> Fix: deletable_by_viewer processing

app/views/passwords/show.html.haml
=> Add No Translate tags to Password element

app/controllers/passwords_controller.rb, config/environment.rb, test/integration/password_creation_test.rb, test/integration/password_json_creation_test.rb
=> Fix Deletable by viewer processing; Add Tests

.do/deploy.template.yaml, README.md
Right now, integrating Digital Ocean support is a minefield of bad documentation and things that just don't work.  As much as I like DO, maybe we'll revisit next year to see if their app platform has matured.
=> Remove DigitalOcean App Platform Support: Revisit next year if they mature

.github/workflows/image.yml, app/helpers/application_helper.rb, app/views/passwords/show.html.erb, app/views/passwords/show_expired.html.erb
- Remove page title branding from password pages
- Build _latest_ docker containers daily
=> Release Touchups

Gemfile.lock, config/puma.rb, docker/pwpush-ephemeral/Dockerfile
- Update puma and improve config
- Avoid using foreman as its messing up the env
=> Docker <--> Puma improvements

.github/workflows/image.yml, README.md, containers/docker/RELEASE.md, containers/docker/pwpush-ephemeral/docker-compose.yaml, containers/docker/pwpush-openshift/template-with-buildconfig.yaml, containers/docker/pwpush-postgres/docker-compose.yaml
=> Docker: Create and make 'release' tag standard

config/initializers/translation.rb, config/settings.yml
- Add Hungarian Language Support
- Maintain alphabetical list
=> Add Hungarian Language Support

containers/docker/pwpush-ephemeral/Dockerfile, containers/docker/pwpush-mysql/Dockerfile, containers/docker/pwpush-openshift/Dockerfile, containers/docker/pwpush-postgres/Dockerfile, yarn.lock
- Yarn package updates
- Update Docker base images to ruby:3.0.4
=> May 4 Dependency Updates

app/views/passwords/show.html.erb
=> Move Clipboard button down

Configuration.md, app/helpers/application_helper.rb, app/models/feedback.rb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/layouts/application.html.erb, app/views/layouts/bare.html.erb, app/views/layouts/login.html.erb, app/views/layouts/naked.html.erb, app/views/shared/_email_footer.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb, config/settings.yml
This PR adds the ability to change:
* Site name
* Site tagline
* Site icon
Fixes #248
=> New Site Branding Ability

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/models/password.rb, app/models/user.rb, app/views/devise/registrations/token.html.erb, app/views/pages/tools.html.erb, app/views/passwords/preview.html.erb, app/views/shared/_header.html.erb, config/initializers/apipie.rb, config/initializers/oj.rb, config/routes.rb, db/migrate/20220816102729_add_authentication_token_to_users.rb, db/schema.rb, gemfiles/Gemfile-mysql, gemfiles/Gemfile-mysql.lock, test/controllers/dashboard_controller_json_test.rb, test/controllers/dashboard_controller_test.rb, test/integration/password_json_audit_test.rb, test/integration/password_json_creation_test.rb, test/integration/password_json_deletion_test.rb, test/integration/password_json_preview_test.rb, test/integration/password_json_retrieval_test.rb
This adds a new API token to user accounts that allows for authenticated JSON API access.
=> API Token Authentication

Configuration.md, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/environments/development.rb, config/environments/private.rb, config/environments/production.rb, config/initializers/lograge.rb, config/initializers/rack-timeout.rb, config/settings.yml, lib/tasks/pwpush.rake
New environment variable `LOG_LEVEL' set the logging level for the application dynamically.
Valid values are `debug`, `info`, `warn`.
=> Better logging with lograge

app/helpers/application_helper.rb, app/models/feedback.rb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/layouts/application.html.erb, app/views/layouts/bare.html.erb, app/views/layouts/login.html.erb, app/views/layouts/naked.html.erb, app/views/passwords/audit.html.erb, app/views/passwords/preview.html.erb, app/views/shared/_email_footer.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb, app/views/shared/_layout_icons.html.erb, config/environments/development.rb, config/environments/private.rb, config/environments/production.rb, config/initializers/devise.rb, config/initializers/translation.rb
=> Add Safeties before using Settings

Configuration.md, app/frontend/js/pw_generator.js, config/defaults/settings.yml, config/settings.yml
=> Password Generator: Add Standard Configurability

containers/docker/pwpush-ephemeral/Dockerfile, containers/docker/pwpush-ephemeral/entrypoint.sh, containers/docker/pwpush-mysql/entrypoint.sh, containers/docker/pwpush-postgres/entrypoint.sh
- pwpush-ephemeral: migrate and compile on container boot
- update entrypoints for postgres and mysql containers
=> Docker Containers: Better boot process

app/views/passwords/new.html.erb, test/integration/password_creation_test.rb
=> Add spellcheck=false to textarea

app/frontend/js/bootstrap_js_files.js, app/views/shared/_header.html.erb, config/defaults/settings.yml, config/settings.yml, package.json, yarn.lock
=> Change Language Selector to Modal

app/views/shared/_header.html.erb, yarn.lock
=> Dependency Updates

lib/tasks/pwpush.rake
When 7.1 comes out, I'll update to disable the use of ranges:
https://blog.kiprosh.com/rails-7-1-optimizes-active-record-batching-for-whole-table-iterations/
=> Background Jobs: Execute in batches

lib/tasks/pwpush.rake
Reverts pglombardo/PasswordPusher#490
This actually uses more memory than less.  Not a clear improvement so it's out.
=> Revert "Background Jobs: Execute in batches"

config/settings.yml
Signed-off-by: Martin Stenröse <martin.stenrose@oderland.se>
=> Fix Catalan and Swedish flag

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, .github/release-drafter.yml, .github/workflows/greetings.yml, .github/workflows/release-drafter.yml, CODE_OF_CONDUCT.md
Enable more Github features like release drafter, extended dependabot & issues/pr templates.
None
=> Enable more Github features

Gemfile, Gemfile.lock, gemfiles/mysql/Gemfile, gemfiles/mysql/Gemfile.lock
Fixes deprecated chrome webdrivers.
None
=> Switch to webdrivers for Selenium

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/workflows/greetings.yml
Updated PR, issue and bug report templates.
=> Updated Github templates

LICENSE
Relicense the project to be more friendly to organisations using Password Pusher.
=> Change License to Apache 2.0

Configuration.md, config/defaults/settings.yml, config/routes.rb, config/settings.yml
Fix for when generated push URLs were no constructed correctly.
=> Fix push URLs with a Relative Root

app/controllers/file_pushes_controller.rb, app/frontend/js/controllers/multi_upload_controller.js, app/views/file_pushes/active.html.erb, app/views/passwords/active.html.erb, app/views/passwords/new.html.erb
- Fix 10 file limit enforcement client & server side
- Fix buttons and a string
=> Fix 10 File Limit Enforcement

app/controllers/urls_controller.rb
Fix the expired partial for URLs.
=> URLs: Fix expired partial

app/views/urls/preview.html.erb
Fixup and improve the text on the URL preview page.
=> URL: Fix preview page text

Gemfile, Gemfile.lock, config/environments/private.rb, config/environments/production.rb, gemfiles/mysql/Gemfile, gemfiles/mysql/Gemfile.lock
=> Switch from Uglifier to ES6 compatible terser

containers/docker/pwpush-ephemeral/Dockerfile, containers/docker/pwpush-mysql/Dockerfile, containers/docker/pwpush-openshift/Dockerfile, containers/docker/pwpush-postgres/Dockerfile
Node.js and yarn have been removed from the project.  They can be removed from the containers.
=> Remove Node.js and Yarn from Docker containers

.gitignore, bin/dev, bin/importmap
New binaries with the latest framework upgrade.
=> Add new Rails binaries

app/javascript/controllers/form_controller.js, app/javascript/controllers/knobs_controller.js, app/views/file_pushes/new.html.erb, app/views/passwords/new.html.erb, app/views/urls/new.html.erb
Better button disabling on form submit
Fix the ActiveStorage upload progress indicators
=> Fix ActiveStorage Uploads, Form Submits & Button Disabling

app/views/file_pushes/new_anonymous.html.erb, app/views/urls/new_anonymous.html.erb, test/controllers/file_push_controller_test.rb, test/controllers/urls_controller_test.rb
Remove the beta notice and links to twitter and github discussion forums.
Switch to a simple login request.
=> Files & URLs: Cleanup login page

app/views/file_pushes/show.html.erb, app/views/passwords/show.html.erb
Remove the spaces from the payload element.
=> Fix: Copy Payload Has Spaces

app/views/devise/shared/_links.html.erb, app/views/file_pushes/new.html.erb, app/views/passwords/new.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb, app/views/urls/new.html.erb
A few improvements based of the W3C HTML check.
=> HTML linter fixups

containers/docker/pwpush-ephemeral/Dockerfile, containers/docker/pwpush-mysql/Dockerfile, containers/docker/pwpush-postgres/Dockerfile
Have the Docker container processes run as a non-root user.
https://nickjanetakis.com/blog/running-docker-containers-as-a-non-root-user-with-a-custom-uid-and-gid
https://docs.docker.com/engine/reference/builder/#arg
=> Run container processes with a dedicated user

Gemfile, Gemfile.lock, gemfiles/mysql/Gemfile, gemfiles/mysql/Gemfile.lock
=> Version min limit boostrap

containers/docker/pwpush-ephemeral/Dockerfile, containers/docker/pwpush-mysql/Dockerfile, containers/docker/pwpush-postgres/Dockerfile
The newly merged PR #561 broke the container building.
This fixes the issue and allows proper run as dedicated user
=> Fix for latetest dockerfile changes

lib/tasks/pwpush.rake
The rake tasks should respect the app settings and be less verbose.
=> Improved Rake Tasks (Background Jobs)

app/views/pages/about.html.erb, app/views/shared/_newsletter_sign_up.html.erb
=> Add newsletter link (pwpush.com only)

app/controllers/application_controller.rb, config/initializers/lograge.rb
=> Better Log Format

LICENSE, config/initializers/apipie.rb
=> Updated copyright dates

app/views/pages/about.html.erb, app/views/pages/generate_key.html.erb, app/views/pages/translate.html.erb
=> Updated About: Help Out Section

app/controllers/file_pushes_controller.rb
=> File Push: Add data safety

app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb, test/integration/file_push/file_push_json_creation_test.rb, test/integration/password/password_json_creation_test.rb, test/integration/url/url_json_creation_test.rb
=> Turbo: Switch to unprocessable_entity for error responses

Gemfile, Gemfile.lock, config/initializers/devise.rb
=> Devise: Update to fix Turbo issues

lib/tasks/pwpush.rake
=> Background Job: Reset counters on completion

app/controllers/application_controller.rb
Second attempt to fix #633.
Fixes #633
=> Default Locale: Use custom handler to force default fallback

app/views/passwords/new.html.erb
=> Fix: Language String

containers/examples/pwpush-and-nginx/docker-compose.yml, containers/examples/pwpush-and-nginx/env-file, containers/examples/pwpush-and-nginx/nginx.conf
=> Nginx Example: Update to fix headers

app/views/shared/_footer.html.erb
=> Footer: Reorg and Add JSON API item

Configuration.md, app/controllers/passwords_controller.rb, app/views/passwords/show.html.erb, config/defaults/settings.yml, config/settings.yml
- Settings: Add option to disable Password Push blurring
- Add option to documentation
Fixes #486
=> Settings: Add Option to Disable Blur Effect on Payload Delivery

.github/workflows/docker-containers.yml
This PR includes:
- Fixes not working dispatch option build (a dollar sign was missing)
- Refactor the docker build action to use matrix build which dedupes copied jobs
- Adds an option to not push to docker hub when running build action manually.
This could be useful while testing docker build changes
=> DOCKER: Improve docker build action on github

.github/workflows/greetings.yml
=> Greeter: Update version and set permissions

test/integration/locales/locales_test.rb
=> Locales: Add more tests

Gemfile, Gemfile.lock
=> Rack Throttle: Version Limit until migration

Gemfile, Gemfile.lock
=> Devise: Update to 4.9.0

containers/docker/pwpush-ephemeral/Dockerfile, containers/docker/pwpush-mysql/Dockerfile, containers/docker/pwpush-postgres/Dockerfile
This fixes 500 on some language locales
=> Locale: Add LC environment variables

Configuration.md, app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/views/file_pushes/show.html.erb, app/views/passwords/preview.html.erb, app/views/passwords/show.html.erb, config/defaults/settings.yml, config/settings.yml, test/integration/file_push/file_push_blur_test.rb, test/integration/file_push/file_push_deletion_test.rb, test/integration/password/password_blur_test.rb, test/integration/password/password_creation_test.rb, test/integration/password/password_deletion_test.rb
This fixes #894 and adds the configuration option to files as well.
#894
=> Blur: Fix Feature and add config to Files

Gemfile, Gemfile.lock
Reverts pglombardo/PasswordPusher#916
=> Revert ":arrow_up: Bump rack-throttle from 0.7.0 to 0.7.1"

app/views/pages/about.html.erb
=> About: Updated links

app/views/urls/new.html.erb
=> URLs: Fix max value setting

app/views/layouts/_ga.html.erb
=> Updated Google Analytics tags

app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb, app/helpers/urls_helper.rb, app/models/file_push.rb, app/models/password.rb, app/models/url.rb, app/views/file_pushes/audit.html.erb, app/views/file_pushes/new.html.erb, app/views/file_pushes/passphrase.html.erb, app/views/passwords/audit.html.erb, app/views/passwords/new.html.erb, app/views/passwords/passphrase.html.erb, app/views/urls/audit.html.erb, app/views/urls/new.html.erb, app/views/urls/passphrase.html.erb, config/routes.rb, db/migrate/20230406094931_add_passphrase_to_models.rb, db/schema.rb, test/controllers/urls_controller_test.rb, test/integration/file_push/file_push_creation_test.rb, test/integration/file_push/file_push_deletion_test.rb, test/integration/file_push/file_push_passphrase_test.rb, test/integration/password/password_json_passphrase_test.rb, test/integration/password/password_passphrase_test.rb, test/integration/url/url_passphrase_test.rb
- Passphrase lockdown option
- Add tests
=> New support for Push Passphrases

app/controllers/file_pushes_controller.rb, test/integration/file_push/file_push_deletion_test.rb, test/integration/file_push/file_push_json_audit_test.rb, test/integration/file_push/file_push_json_creation_test.rb, test/integration/file_push/file_push_json_deletion_test.rb, test/integration/file_push/file_push_json_passphrase_test.rb, test/integration/file_push/file_push_json_preview_test.rb, test/integration/file_push/file_push_json_retrieval_test.rb, test/integration/file_push/file_push_notfound_test.rb, test/integration/file_push/file_push_passphrase_test.rb, test/integration/file_push/file_push_retrieval_test.rb
=> Improve and add many tests; Fix File Push access bug

app/controllers/passwords_controller.rb
=> Update API documentation

containers/docker/pwpush-mysql/docker-compose-mariadb.yml, containers/docker/pwpush-mysql/docker-compose-mysql.yml
=> Provide two MySQL Docker Compose Files: MySQL & MariaDB

db/migrate/20230406094931_add_passphrase_to_models.rb, db/migrate/20230420175410_fix_passphrase_default.rb, db/schema.rb
=> Passphrase: Remove Column Defaults

app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb, db/migrate/20230420175410_fix_passphrase_default.rb
=> Passphrase Lockdown: null handling

app/views/file_pushes/passphrase.html.erb, app/views/passwords/passphrase.html.erb, app/views/shared/_dashboard_header.html.erb, app/views/urls/passphrase.html.erb
=> Translations: Add missing strings

app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb
=> API Docs: Specify that payloads should be URL encoded

app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb
=> Update API docs with passphrase documentation

config/defaults/settings.yml, config/initializers/translation.rb, config/settings.yml
=> Add ability to disable individual languages

app/views/shared/_header.html.erb
=> Language Modal: 4 languages per row

lib/tasks/pwpush.rake
=> Update File Purge background task

app/views/devise/shared/_links.html.erb, app/views/shared/_header.html.erb, app/views/shared/_lang_selector_modal.erb
=> Updated language selector for login pages

README.md
"it's" should be "its" in these two cases.
See [dictionary blog post](https://www.merriam-webster.com/words-at-play/when-to-use-its-vs-its) if you're curious
=> Fix README.md punctuation

Gemfile, Gemfile.lock
=> Update Gemfile Ruby Version

app/assets/stylesheets/application.scss.erb, config/defaults/settings.yml, config/settings.yml
Better display of flags with white on a white background:
=> Improved Country Flag Styling

app/helpers/application_helper.rb
=> Fix URL creation with base URL overrides

Gemfile, Gemfile.lock, app/controllers/feedbacks_controller.rb, app/models/feedback.rb, app/views/feedbacks/create.html.erb, app/views/feedbacks/new.html.erb
- Improve the Feedback form with redirect and notice
- Cleanup
=> Improved Feedback Form

.github/workflows/docker-containers.yml
Was unfortunately disabled with last PR.
=> Add image push back

Gemfile.lock
=> Bundler update

app/controllers/file_pushes_controller.rb
=> Remove File Upload limit for self-hosted

config/defaults/settings.yml, config/environments/development.rb, config/environments/private.rb, config/environments/production.rb, config/settings.yml
=> Add Array support to PWP__ALLOWED_HOSTS

containers/docker/pwpush-ephemeral/entrypoint.sh, containers/docker/pwpush-mysql/entrypoint.sh, containers/docker/pwpush-postgres/entrypoint.sh
=> Better container precompile boot message

app/assets/stylesheets/themes/cerulean.css, app/assets/stylesheets/themes/cosmo.css, app/assets/stylesheets/themes/cyborg.css, app/assets/stylesheets/themes/darkly.css, app/assets/stylesheets/themes/flatly.css, app/assets/stylesheets/themes/journal.css, app/assets/stylesheets/themes/litera.css, app/assets/stylesheets/themes/lumen.css, app/assets/stylesheets/themes/lux.css, app/assets/stylesheets/themes/materia.css, app/assets/stylesheets/themes/minty.css, app/assets/stylesheets/themes/morph.css, app/assets/stylesheets/themes/pulse.css, app/assets/stylesheets/themes/quartz.css, app/assets/stylesheets/themes/sandstone.css, app/assets/stylesheets/themes/simplex.css, app/assets/stylesheets/themes/sketchy.css, app/assets/stylesheets/themes/slate.css, app/assets/stylesheets/themes/solar.css, app/assets/stylesheets/themes/spacelab.css, app/assets/stylesheets/themes/superhero.css, app/assets/stylesheets/themes/united.css, app/assets/stylesheets/themes/vapor.css, app/assets/stylesheets/themes/yeti.css, app/assets/stylesheets/themes/zephyr.css, lib/tasks/pwpush.rake
=> Update bundled themes to latest versions

Gemfile, Gemfile.lock
Reverts pglombardo/PasswordPusher#1382
=> Revert ":arrow_up: Bump bootstrap from 5.2.3 to 5.3.1"

app/views/pages/faq.html.erb
=> faq typo fix

app/views/pages/generate_key.html.erb
=> Fix copy to clipboard buttons on Generate Key page

app/views/shared/_footer.html.erb, config/defaults/settings.yml, config/settings.yml
My initial attempt at showing a disclaimer.  Feedback is highly welcomed.
Not sure if the combination of `class` and `style` is the best.  Bootstrap != Tailwind, so I was a bit stuck.
Tested the container using:
```
docker run --rm -it -p "8000:5100" -e PWP__BRAND__DISCLAIMER="This is a dummy disclaimer and should not be considered legally binding or taken seriously in any way. The content provided here is for entertainment and illustrative purposes only. Any resemblance to actual disclaimers is purely coincidental. We do not endorse or encourage the use of this disclaimer for any real-world applications, and we strongly advise consulting a legal professional for creating legitimate and appropriate disclaimers for your specific needs. By reading this disclaimer, you agree not to hold us …
```
=> feat: add support for showing a disclaimer

README.md, containers/docker/README.md, containers/docker/RELEASE.md, containers/docker/pwpush-docker-env-file, containers/examples/pwpush-and-nginx/docker-compose.yml, containers/helm/values.yaml, containers/kubernetes/ephemeral_deploy.yaml, containers/kubernetes/persistent_deploy.yaml
This PR updates documentation files convering newly itroduced universal docker image.
This refers to https://github.com/pglombardo/PasswordPusher/pull/1369
=> Updated doc files due to new docker image

Configuration.md, containers/examples/pwpush-and-nginx/env-file
Noticed it was missing in various places.  This tries to bring it up to speed.
=> docs: update disclaimer examples

.rubocop.yml, app/controllers/feedbacks_controller.rb, app/models/feedback.rb, app/views/feedbacks/new.html.erb, test/models/feedback_test.rb
- Better Feedback Form Spam Checks
- Set reply-to
=> Feedback: Better Spam Checks

app/models/feedback.rb
=> Feedback Spam: A few more for the check

app/controllers/urls_controller.rb, test/integration/url/url_passphrase_test.rb
=> URL Pushes: Workaround for CORS bug in redirect

app/models/feedback.rb
=> Feedback: More filters

README.md
=> Minor Change based on branch name

config/defaults/settings.yml, config/settings.yml, config/storage.yml
See #1567 for details.
Fixes #1567
=> Add Support for IAM and Workload Identity on GCS

app/views/devise/registrations/token.html.erb, app/views/devise/shared/_links.html.erb, app/views/file_pushes/show.html.erb, app/views/layouts/application.html.erb, app/views/layouts/bare.html.erb, app/views/layouts/login.html.erb, app/views/layouts/naked.html.erb, app/views/pages/about.html.erb, app/views/passwords/new.html.erb, app/views/passwords/show.html.erb, app/views/shared/_header.html.erb
`Rendered shared/_layout_icons.html.erb (Duration: 87.3ms | Allocations: 140709)`
Allocations: 140709 👀 
By adding cached option:
`<%= render partial: "shared/layout_icons", cached: true %>`
we get:
`Rendered shared/_layout_icons.html.erb (Duration: 3.6ms | Allocations: 7227)`
Allocations: 7227 👀
=> Performance: Cache static partials

app/assets/javascripts/application.js, app/javascript/controllers/application.js, app/javascript/controllers/gdpr_controller.js, app/javascript/controllers/index.js, app/views/layouts/application.html.erb, app/views/shared/_cookie_consent.html.erb
=> GDPR: Add cookie consent notice

Configuration.md, app/views/shared/_cookie_consent.html.erb, config/defaults/settings.yml, config/settings.yml
=> Make Cookie Consent Feature Configurable

app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/layouts/application.html.erb, app/views/layouts/bare.html.erb, app/views/layouts/login.html.erb, app/views/layouts/naked.html.erb
=> Update flag-icons to 7.1.0

Gemfile, Gemfile.lock
=> Remove Profiler

Gemfile, Gemfile.lock
Move the `i18n-tasks` gem to the development group to save about ~20MB of memory.
=> Small Memory Improvement

containers/docker/Dockerfile
=> Add SECRET_KEY_BASE to Dockerfile

app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb
=> API Docs: Fix retrieval_step valid values

app/models/feedback.rb
=> Feedback: Add More Spam Traps

app/views/shared/_layout_icons.html.erb
=> Meta Tags: Add Twitter and OpenGraph

app/views/shared/_cookie_consent.html.erb
=> GDPR: Fix banner translations

app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb
=> Remove deprecated jsdelivr links

config/defaults/settings.yml, config/settings.yml
=> Pre-compilation: Update yaml file with documentation

app/views/pages/tools.html.erb
This PR updates the Tool Page:
* Remove Slack documentation (non-functional)
* Update to latest KpPwpush package by @thekamilpro
=> Updated Tools Page

app/views/pages/tools.html.erb
=> Tools Page: Update the Browser Code Example

app/views/pages/faq.html.erb
=> Small FAQ updates

Configuration.md, config/defaults/settings.yml, config/initializers/settings.rb, config/routes.rb, config/settings.yml
=> Remove the deprecated relative_root option

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss.erb, app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb, app/views/file_pushes/active.html.erb, app/views/file_pushes/expired.html.erb, app/views/passwords/active.html.erb, app/views/passwords/expired.html.erb, app/views/urls/active.html.erb, app/views/urls/expired.html.erb
=> Migrate from Will Paginate to Kaminari

app/dashboards/user_dashboard.rb
=> Admin Dashboard: Show Creation Date & Sign In Count to Users Display

app/views/file_pushes/show.html.erb
=> Add nil safety

app/dashboards/user_dashboard.rb
- **Admin Dashboard: Fix for User Creation**
- **Confirmation not required**
Fixes #2008
=> Admin Dashboard: Fix for User Creation

app/controllers/base_controller.rb, app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb
=> ActionController::UnknownFormat: Centralize Handler

Configuration.md, README.md, app/views/pages/faq.html.erb, containers/docker/docker-compose-ephemeral.yml, containers/docker/docker-compose-mariadb.yml, containers/docker/docker-compose-mysql.yml, containers/docker/docker-compose-postgres.yml, containers/docker/pwpush-docker-env-file, containers/examples/pwpush-and-nginx/docker-compose.yml
=> Update Docker tag references

.github/workflows/ruby-tests.yml, db/migrate/20240407113632_add_indexes_to_view.rb, db/schema.rb
=> DB: Add Indexes to Views Table

config/initializers/devise.rb
=> Send notification on password change

app/mailers/test_mailer.rb, config/defaults/settings.yml, config/settings.yml
=> TestMailer: Add more checks

app/models/file_push.rb, app/models/password.rb, app/models/url.rb, app/views/file_pushes/audit.html.erb, app/views/passwords/audit.html.erb, app/views/urls/audit.html.erb
=> Set default sort for Views

app/controllers/urls_controller.rb, app/views/urls/passphrase.html.erb
=> URLs: Direct redirect after passphrase & disable turbolinks for form

app/helpers/application_helper.rb
=> QR Code: Support for Dark Mode

config/defaults/settings.yml, config/environments/development.rb, config/environments/production.rb, config/settings.yml
=> SMTP: Allow for NOAUTH

app/controllers/urls_controller.rb, app/views/urls/passphrase.html.erb, test/integration/url/url_passphrase_test.rb
This fixes the issue pointed out in [this comment](https://github.com/pglombardo/PasswordPusher/issues/1997#issuecomment-2076157943).
=> Fix: URL View Tracking

app/views/shared/_footer.html.erb
=> Footer: Fix Copyright Year

containers/docker/Dockerfile
Ruby 3.3.1 should have the fix that cause #1761
=> Update Docker container to Ruby 3.3.1

containers/docker/Dockerfile
I missed updating the 2nd phase Docker part.
=> Docker: Fix Ruby Update

app/controllers/urls_controller.rb, test/integration/url/url_json_retrieval_test.rb
=> URLs: Document JSON API Passphrase Usage

app/controllers/base_controller.rb
=> Rescue from ActionController::BadRequest

config/environments/development.rb, config/environments/production.rb
=> Mail: Fix value checks

Gemfile, Gemfile.lock, app/controllers/users/registrations_controller.rb, app/views/devise/registrations/new.html.erb
If no issues come up with this captcha, I'll extend this to the login and feedback forms.
=> Add Captcha to New User Registration

containers/docker/all-in-one/Caddyfile
=> Caddy: Add Secure Cookies Policy

.github/workflows/greetings.yml
=> Fix New Contributor Greeting

config/routes.rb, test/integration/admin_dashboard_test.rb
=> Add Admin Route Protection

app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb, test/integration/file_push/file_push_deletion_test.rb, test/integration/password/password_deletion_test.rb
=> 1-click: Immediately show expired message if push is expired

app/views/pages/about.html.erb, app/views/shared/_footer.html.erb
We've have now reached 31 translated languages.  Thanks to all the volunteers!
31 is a big number and we've covered most of the major languages.  Each language was added through user request.
For the time being, I won't be adding anymore languages although I may resume in the future.  If an unsupported language is critical to your org, please let me know.  I can probably add it.
For the time being, I want to focus on bigger and better features coming soon.
=> Remove Help Translate Links

app/views/shared/_footer.html.erb
=> Add Documentation Link

config/defaults/settings.yml, config/settings.yml
=> Fix Settings.yml Typo

Gemfile, Gemfile.lock, config/initializers/route_translator.rb
=> Remove route_translate gem

app/assets/stylesheets/application.scss.erb, config/initializers/assets.rb, package.json, yarn.lock
=> Remove Flag Icons Set

README.md
Fixed link to third-party tools after readme restructure.
=> fixed link to 3rd party tools in README.md

.github/workflows/docker-containers.yml, app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb, config/routes.rb, config/routes/admin.rb, config/routes/public_pushes.rb, config/routes/public_users.rb, config/routes/pushes.rb, config/routes/users.rb, containers/docker/Dockerfile.public-gateway
This PR introduces a new container `pglombardo/pwpush-public-gateway`.
This container offers a reduced set of routes & functionality targeted at _only_ deliverying pushes to end users.  There is not logins, no admin dashboard and nothing else.
Documentation with a better explaination to come.
- **New Public Gateway Container**
- **New container build**
=> New Public Gateway Container

Gemfile, Gemfile.lock, config/application.rb
=> Application Framework Updates

Gemfile, Gemfile.lock, config/initializers/lograge.rb, config/puma.rb
=> Framework: Puma, Lograge Updates & Remove rack-timeout

containers/docker/Dockerfile
=> Dockerfile updates to follow Rails 7.2

app/controllers/urls_controller.rb, app/helpers/application_helper.rb, test/controllers/file_push_controller_test.rb, test/integration/password/password_json_preview_test.rb
=> Fix Override Base URL Construction

Gemfile, app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb, app/helpers/application_helper.rb, test/integration/file_push/file_push_requested_locale_test.rb, test/integration/password/password_requested_locale_test.rb, test/integration/url/url_requested_locale_test.rb
=> Pass locale through preliminary step

Gemfile, Gemfile.lock, app/views/layouts/application.html.erb, config/initializers/sentry.rb
To diagnose issues in production, adding Sentry for performance monitoring.
=> Add Sentry for APM

.overcommit.yml, Gemfile, Gemfile.lock
=> Add Overcommit for local development

config/initializers/translation.rb
=> Enabled Language Codes: Ensure Array

app/controllers/file_pushes_controller.rb
=> Fix: Better upload count check

app/views/application/_secret_url_bar.html.erb, app/views/file_pushes/audit.html.erb, app/views/file_pushes/preview.html.erb, app/views/passwords/audit.html.erb, app/views/passwords/preview.html.erb, app/views/urls/audit.html.erb, app/views/urls/preview.html.erb, config/locales/pwpx.en.yml
=> Simplify Secret URL bar

.github/workflows/docker-containers.yml, Gemfile, Gemfile.lock, Procfile, Procfile.dev, app/jobs/clean_up_pushes_job.rb, app/jobs/expire_pushes_job.rb, bin/jobs, config/environments/production.rb, config/queue.yml, config/recurring.yml, config/routes/admin.rb, containers/docker/Dockerfile.worker, containers/docker/worker-entrypoint.sh, db/migrate/20241008192458_add_solid_queue.rb, db/schema.rb
This PR adds a new docker container `pwpush-worker` that can be run to execute periodic background tasks.
#468
=> New pwpush-worker Docker container

test/integration/file_push/file_push_creation_test.rb
=> Tests: Add test to validate file upload limits

.github/workflows/ruby-tests.yml
=> CI: Update tests to use Ruby 3.3

app/views/file_pushes/preliminary.html.erb, app/views/file_pushes/preview.html.erb, app/views/passwords/preliminary.html.erb, app/views/passwords/preview.html.erb, app/views/urls/preliminary.html.erb, app/views/urls/preview.html.erb
=> Disable prefetch on secret URLs

config/initializers/cookies_serializer.rb, containers/docker/Dockerfile
This fixes https://github.com/pglombardo/PasswordPusher/security/code-scanning/1 re: cookie serialization.
This PR also rotates the secret key base to invalidate all previous sessions.
=> Security: Use json for cookie serialization

app/views/devise/confirmations/show.html.erb
=> Sanitize Confirmation Parameter

app/jobs/clean_up_pushes_job.rb, app/jobs/expire_pushes_job.rb
=> Background Jobs: Fix environment variable check

yarn.lock
=> Yarn package updates

app/controllers/passwords_controller.rb
=> Special fix for Mariadb

containers/docker/Dockerfile, containers/docker/docker-compose-ephemeral.yml, containers/docker/docker-compose-mariadb.yml, containers/docker/docker-compose-mysql.yml, containers/docker/docker-compose-postgres.yml, containers/docker/entrypoint.sh
This PR fixes the problems described in #2905 related to release v1.50.0.
#2905
=> Fix: Custom theme setup on container boot

app/assets/stylesheets/themes/cyborg.css
This fixes the issue with the Cyborg theme reported [here](https://github.com/pglombardo/PasswordPusher/issues/2905#issuecomment-2559291056).
Thanks @thomaspark for the fix and all the great themes!
https://github.com/thomaspark/bootswatch/issues/1319
=> Cyborg Theme: Upstream Bootswatch Fix

containers/docker/Dockerfile
=> Docker Builds: Include yaml-dev for psych lib

.github/workflows/docker-containers.yml, bin/move_up_stable_tag.sh
=> Tools: New Docker release tagging script

app/views/file_pushes/preliminary.html.erb, app/views/passwords/preliminary.html.erb, app/views/urls/preliminary.html.erb
https://github.com/pglombardo/PasswordPusher/issues/2225
=> Fix: Block preliminary pre-loading

containers/docker/Dockerfile
=> Fix Alpine build issue

containers/docker/Dockerfile
=> Restore Bootsnap

app/assets/stylesheets/application.bootstrap.scss, app/javascript/controllers/application.js
=> Fix Theme Switching via Media Query

bin/move_up_stable_tag.sh
=> Reconstitute "stable" tag in git

app/javascript/application.js, app/javascript/controllers/application.js
In the latest Docker containers, the JS to detect system light/dark mode wasn't triggering correctly.
This PR moves the detection code to a better place.
=> Themes: Fix JS mode switching

containers/docker/Dockerfile
=> Docker: Build javascript in stage 1

config/defaults/settings.yml, config/settings.yml
=> Fix: Add missing underscore

Gemfile, test/test_helper.rb
=> Fix Warning: parser/current is loading parser/ruby34

config/routes.rb
=> Add /up healthcheck endpoint

app/views/application/_ip_address.html.erb, app/views/file_pushes/audit.html.erb, app/views/passwords/audit.html.erb, app/views/urls/audit.html.erb
=> Audit Log: Move IP rendering out to partial

app/controllers/users/registrations_controller.rb, app/models/concerns/pwpush/token_authentication.rb, app/models/user.rb, test/controllers/password_controller_test.rb
API Token regeneration was broken in the last release.
=> Fix: Token Regeneration

Gemfile, Gemfile.lock, app/controllers/users/registrations_controller.rb, bin/dev
Fixes an error 500 when anonymous accessing /users/token
- **Fix: better redirect rendering**
- **Switch to overmind**
=> Fix: Better redirect handling

app/views/layouts/login.html.erb
=> Fix: Login Pages Logo Formatting

app/views/shared/_header.html.erb
=> Fix: Logout Menu Item

app/controllers/file_pushes_controller.rb, app/controllers/passwords_controller.rb, app/controllers/urls_controller.rb, app/views/layouts/application.html.erb, app/views/layouts/bare.html.erb, app/views/layouts/login.html.erb, app/views/layouts/naked.html.erb
=> Fix: Update Passphrase Cookie & TurboDrive Default Settings

app/controllers/csp_reports_controller.rb, config/initializers/content_security_policy.rb, config/routes.rb
First release with a loose security policy.  As things are proven, I'll attempt to tighten the security policy incrementally.
=> New Content Security Policy

containers/docker/Dockerfile
Using `jemalloc` can give big reductions in memory usage.  It's an easy addition with big benefits.
=> Performance: Add jemalloc

app/views/file_pushes/preview.html.erb, app/views/passwords/preview.html.erb, app/views/urls/preview.html.erb
=> Fix: Block preloading on "View Now" link

.github/workflows/docker-containers.yml
=> Restore Docker arm64 builds

config/recurring.yml
=> Bundled Worker with Automatic Recurring Background Jobs

Procfile
=> Fix: Foreman port ordering

containers/docker/entrypoint.sh
=> Docker: Set default port to 5100

.rubocop.yml, Gemfile, Gemfile.lock
This PR updates selenium-webdriver to address a CVE identified in https://github.com/pglombardo/PasswordPusher/discussions/3250
https://github.com/pglombardo/PasswordPusher/discussions/3250
=> Security: Update selentium-webdriver

app/views/file_pushes/preview.html.erb, app/views/passwords/preview.html.erb, app/views/urls/preview.html.erb
=> Preview: Improved expiration message

README.md
=> Fix the Spanish translation link

config/initializers/lockbox.rb
Add initial support for encryption key rotation: https://github.com/ankane/lockbox?tab=readme-ov-file#key-rotation
=> Encryption: Add ability for key rotation

app/controllers/passwords_controller.rb
=> Fix: Print preview does not require an authenticated session

config/puma.rb, config/queue.yml
This should further reduce Docker container memory.
It changes Puma to run in single process mode.
=> Memory: Run Puma in single mode

containers/docker/docker-compose-ephemeral.yml, containers/docker/docker-compose-mariadb.yml, containers/docker/docker-compose-mysql.yml, containers/docker/docker-compose-postgres.yml
=> Docker Compose: Updates

.github/workflows/brakeman.yml, .github/workflows/ruby-tests.yml, Gemfile, Gemfile.lock
Ruby version used by the project is updated.
-
I haven't added any test. Running `rake test` doesn't show any issue. @pglombardo
=> Update ruby version bundling gems

config/defaults/settings.yml, config/settings.yml, config/storage.yml
Added minio support for S3 storage
[#2324](https://github.com/pglombardo/PasswordPusher/issues/2344)
=> feat: Added minio support for S3 storage

app/assets/stylesheets/themes/brite.css, lib/tasks/pwpush.rake
=> Themes: Add new Brite theme from Bootswatch
